### PR TITLE
fix commented SEClamp option

### PR DESCRIPTION
**Pull request by rodriguez-facundo**
There was a problem with metadata. Now it is fix.

just some minor comment: i and vc are not parameters, but observables so I am removing them from SEClamp

### CODE REVIEW

**Comment by adrianq** [comment]
Ok, so metadata branch in netpyne should have the fix, right?

**Comment by rodriguez-facundo** [comment]
yep. I just tried and seems to be working fine

IClamp --> dur & amp are floats
VClamp & SEClamp -->> dur & amp are list (length 3)

**Comment by adrianq** [comment]
Ok, so you created two entried in json structure: netParams.stimSourceParams.dur and netParams.stimSourceParams.vClampDur Just understanding the solution...

**Comment by rodriguez-facundo** [comment]
yes. I could probably separate like this:
netParams.stimSourceParams.vClampDur
netParams.stimSourceParams.SEClampDur

but their are basically the same. Don't know if it is important to keep metadata small. I think many fields are duplicated. Like conditions for cellParams, stimTargetParams, connParams. Making metadata big

**Pull request merged**
